"""Record Studio 3D Importer IDs and generate runtime data; never uploads or spends credits.
First: blender -b -P tools/export_guns.py. Import build/guns-import.glb in Studio with
Upload to Roblox + Insert Using Scene Position enabled, then save build/guns-upload.rbxlx.
python3 tools/import_guns.py --from-place build/guns-upload.rbxlx
Subsequent generation reuses the hash-locked ledger: python3 tools/import_guns.py
"""
import argparse
import json
import xml.etree.ElementTree as ET
from pathlib import Path

R = Path(__file__).resolve().parents[1]
LEDGER = R / 'assets/guns/uploaded-assets.json'

def lua(v):
    if isinstance(v, dict):
        return '{' + ','.join('[' + json.dumps(k) + ']=' + lua(x) for k,x in v.items()) + '}'
    if isinstance(v, list):
        return '{' + ','.join(lua(x) for x in v) + '}'
    return json.dumps(v)

def generate(geo, ledger):
    result = {}
    for gid, gun in geo.items():
        pieces = []
        for p in gun['pieces']:
            entry = ledger.get(p['name'])
            assert entry and entry['sha256'] == p['sha256'] and entry['export_sha256'] == gun['export_sha256'], 'Missing/stale upload: ' + p['name']
            pieces.append({k:v for k,v in p.items() if k not in ('vertices','faces')} | {'assetId': str(entry['assetId']), 'rotation': entry['rotation']})
        result[gid] = {**gun, 'pieces':pieces}
    # Vectors/colors are typed at generation time; runtime needs no JSON parser or vertex construction.
    s = '-- Generated by tools/export_guns.py + tools/import_guns.py; do not edit.\nreturn ' + lua(result) + '\n'
    import re
    for key in ('pivot','center','size','muzzle','Grip','Sight','FrontSight','Barrel','Mag','Mover','Optic','Foregrip','rotation'):
        s = re.sub(r'(\["'+key+r'"\]=)\{([^{}]+)\}', r'\1Vector3.new(\2)', s)
    s = re.sub(r'(\["color"\]=)\{([^{}]+)\}', r'\1Color3.new(\2)', s)
    (R/'src/shared/GunAssets.luau').write_text(s)
    print('BC_GUN_GENERATED', len(result), 'guns')

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--from-place', type=Path)
    args=ap.parse_args()
    geo=json.loads((R/'build/guns-geometry.json').read_text())
    ledger=json.loads(LEDGER.read_text()) if LEDGER.exists() else {}
    if args.from_place:
        root=ET.parse(args.from_place)
        lookup={p['name']:(g,p) for g in geo.values() for p in g['pieces']}
        found={}
        for item in root.findall('.//Item[@class="MeshPart"]'):
            props=item.find('Properties')
            name=props.find('string[@name="Name"]').text
            if name not in lookup: continue
            assert name not in found, 'Duplicate imported piece: '+name
            g,p=lookup[name]
            def vector(key):
                return [float(props.find('*[@name="'+key+'"]/'+a).text) for a in 'XYZ']
            size,center=vector('size'),vector('CFrame')
            assert max(abs(a-b) for a,b in zip(size,p['size'])) < .001, 'Import scale: '+name
            # Studio Front/Top glTF import bakes a 180-degree Y turn into the vertices.
            corrected=[-center[0],center[1],-center[2]]
            assert max(abs(a-b) for a,b in zip(corrected,p['center'])) < .001, 'Import position/axis: '+name
            frame=props.find('CoordinateFrame[@name="CFrame"]')
            assert all(abs(float(frame.find('R'+str(i)+str(j)).text)-(1 if i==j else 0))<.0001 for i in range(3) for j in range(3)), 'Unexpected importer rotation: '+name
            uri=props.find('Content[@name="MeshId"]/url').text
            assert uri.startswith('rbxassetid://') and uri[13:].isdigit(), 'Unpublished mesh: '+name
            found[name]=dict(name=name,assetId=uri[13:],sha256=p['sha256'],export_sha256=g['export_sha256'],rotation=[0,180,0])
        assert set(found)==set(lookup), 'Missing imported pieces: '+str(set(lookup)-set(found))
        ledger=found
        temp=LEDGER.with_suffix('.tmp')
        temp.write_text(json.dumps(ledger,indent=2)+'\n');temp.replace(LEDGER)
        print('BC_GUN_IMPORT',len(found),'uploaded pieces; scale and axes verified')
    generate(geo,ledger)

if __name__=='__main__': main()
